### PR TITLE
Fix the overflow problem by using breakpoint container

### LINKED ISSUE #111: Textüberlappungen bei schmaler Fensterbreite
Ab einer gewissen verfügbaren Breite (und weniger) überlappen Text der Sidebar und des Seiteninhalts.

### PR DESCRIPTION
**Pull request by miterion**
Fixes #111

### CODE REVIEW

**Review by Xiphoseer — APPROVED** [review]

**Comment by Xiphoseer** [comment]
As far as I can tell, this doesn't actually solve the problem of words that are "too long" (like "Studieninteressierte") not breaking into multiple lines, but it does improve the current situation visually. But we can merge it either way if you want.

With this patch applied:
websitebug

**Comment by miterion** [comment]
@Xiphoseer Can you try again after applying 19c1286? Not the best solution but it is at least something and might even look good if the proper language setting and hyphenation data is available.

**Review by joachimschmidt557 — APPROVED** [review]
Thanks! Long items in the navigation list look much better now.

**Comment by miterion** [comment]
Thanks for your reviews. From my perspective this PR can be merged now. Could one of @d120/webseite do this please?

**Pull request merged**
