### PR TITLE
Add eager updater together with new pip resolver to update script

### PR DESCRIPTION
**Pull request by miterion**
This should fix some of the implicit dependency problems by automatically updating all dependencies using the resolver in pip.

### CODE REVIEW

**Review by joachimschmidt557 — APPROVED** [review]
Looks good to me!

**Review by Xiphoseer — APPROVED** [review]

**Comment by Xiphoseer** [comment]
This is propably the cause for the following error that just happened when tyring to deploy #61

```
Installing collected packages: certifi
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.6.20
    Uninstalling certifi-2020.6.20:
      Successfully uninstalled certifi-2020.6.20
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Keine Berechtigung: 'INSTALLER'
Consider using the `--user` option or check the permissions.
```

**Comment by Xiphoseer** [comment]
Weird, I entered the virtualenv and ran the update script again and it worked... But the script loads the venv anyways if that isn't the case already

**Comment by miterion** [comment]
I updated the permissions on the server, it might work now.

**Pull request merged**
