### PR TITLE
Add plugins needed for Ophase

### PR DESCRIPTION
**Pull request by bhaettasch**
We've implemented several plugins that will be of use for the Ophase / digital semester landing page part of the d120 page.

The plugins are based on the DjangoCMS Cascade plugin (requirement added).

The new plugins are:
- **ChangeLogBox**: Plugin to show the last change (publication) timestamp of this page     (together with other plugins indicating the changes if wanted)
- **ToDoListPlugin**: Plugin to create/show a simple to do list that stores its current state in the local browser storage
- **TimelinePlugin**: Plugin to show a vertical timeline
- **MapPlugin**: Embed a custom open street map in the page. This adds a whole lot of frontend dependencies (OpenLayers) with multiple files.

Since this functionality is urgently needed for preparing the webpage, we would appreciate a quick review.

plugins

// @geislern

### CODE REVIEW

**Review by geislern — APPROVED** [review]
Looks good to me, worked on my machine for TODO List, Map, Changelog, Timeline.
Only drawback is having to reload a page after making changes to a page with a map; but I do not see how we could avoid this.

**Review by joachimschmidt557 — APPROVED** [review]
Looks good to me!

**Review by miterion — APPROVED** [review]

**Comment by miterion** [comment]
@d120/webseite Can one of you merge and deploy?

**Comment by geislern** [comment]
Who could do that? :)

**Comment by miterion** [comment]
The changes are now online, please check if everything works as expected @bhaettasch @geislern

**Pull request merged**
